
# cmd
FROM ubuntu:latest

ENTRYPOINT ["/bin/echo", "hello world 1"]
ENTRYPOINT ["/bin/echo", "hello world 2"]
ENTRYPOINT ["/bin/echo", "hello world 3"]
ENTRYPOINT ["/bin/echo", "hello world 4"]
CMD ["/bin/echo", "hello world 5"] 





